name: appcenter
env:
  PROJECT_NAME: app-center
  IMAGE_PREFIX: dockerhub.qingcloud.com/lowcode
  DATE: $(date "+%Y%m%d")
on: [push, pull_request]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: go test ./...
      - run: go test -cover ./...

  deploy_alpha:
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/alpha'
    steps:
      - run: GOOS=linux GOOSARCH=amd64 go build -o ${{ env.PROJECT_NAME }} ./cmd/.
      - run: /root/github-runners/dev_auto.sh ${{ env.PROJECT_NAME }}

  build_test:
    runs-on: self-hosted
    needs: test
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - run: go mod tidy
      - run: go mod vendor
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: docker build -t ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG .
      - run: docker push ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG
      - run: docker rmi ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG

  build_staging:
    runs-on: self-hosted
    needs: test
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - run: echo ${{ github.ref_type }}
      - run: go mod tidy
      - run: go mod vendor
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: docker build -t ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG .
      - run: docker push ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG
      - run: docker tag ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:latest
      - run: docker push ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:latest
      - run: docker rmi ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG

  deploy_test:
    runs-on: self-hosted
    needs: [test,build_test]
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: /opt/upImage.sh ${{ env.IMAGE_PREFIX }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG $GITHUB_REF_NAME

  deploy_staging:
    runs-on: self-hosted
    needs: [test,build_staging]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - run: echo IMAGE_TAG="v${{ env.DATE }}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: helm upgrade ${{ env.PROJECT_NAME }} /root/quanxiang_charts_staging/${{ env.PROJECT_NAME }} --kubeconfig ~/.kube/config_staging --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode
